**DATE**: 1 August 2017 <br>
**ENVIRONMENT**: qiime1 <br>
**AUTHOR**: Max Abramson

The goal of this notebook is to take a full biom table (from the AGP) and trim it down to only include the samples found in a metadata text file. <br>
Unfortunately, there were a handful of samples that did not have enough reads to make it into the biom table, so this notebook filters the biom table, then identifies the samples that are missing from the new biom table, and finally, filters the biom table with a new set of samples that do not include the missing samples or their matched pairs.

In [35]:
import pandas as pd
import numpy as np
import biom
from IPython.display import FileLinks, FileLink

In [1]:
root='/Users/maxabramson/Desktop/Knight_Lab/AGP_depression/AGP_broad_criteria/'
table=root+'otu_table_no_blooms_125nt_with_tax_min1250.biom'
metadata=root+'AGP_bc_subset_metadata.txt'
metadata_222=root+'AGP_bc_subset_metadata_222.txt'

# Initial filtering of biom table
##### This allows us to see which samples were dropped due to low reads or issues with processing

In [7]:
filtered_table=root+'Parse_biom_table/filtered_bc_table.biom'
!filter_samples_from_otu_table.py \
-i $table \
-o $filtered_table \
--sample_id_fp $metadata

In [16]:
table_summary=root+'Parse_biom_table/filtered_bc_table_summary.txt'
!biom summarize-table -i $filtered_table \
-o $table_summary

# Finding the "missing" samples

In [20]:
#Read in the BIOM table summary
otu_table=pd.read_table(table_summary, sep='\t',
                     dtype=str)

In [26]:
otu_table.head(20)

                                     Num samples: 234
0                             Num observations: 49871
1                                Total count: 2477519
2   Table density (fraction of non-zero values): 0...
3                              Counts/sample summary:
4                                         Min: 1678.0
5                                        Max: 88027.0
6                                    Median: 8564.500
7                                     Mean: 10587.688
8                                 Std. dev.: 8476.833
9           Sample Metadata Categories: None provided
10          Observation Metadata Categories: taxonomy
11                              Counts/sample detail:
12                            10317.000059971: 1678.0
13                            10317.000023973: 1682.0
14                            10317.000041126: 1874.0
15                            10317.000052430: 1930.0
16                            10317.000039986: 2040.0
17                            10317.000023965: 2343.0
18                            10317.000042660: 2427.0
19                            10317.000040003: 2493.0

In [27]:
otu_table.set_index("Num samples: 234", inplace=True)

In [28]:
otu_table.head()

Empty DataFrame
Columns: []
Index: [Num observations: 49871, Total count: 2477519, Table density (fraction of non-zero values): 0.004, Counts/sample summary:,  Min: 1678.0]

In [65]:
#Read in the original subset metadata that has the initial samples you wanted.
#None of the missing samples (or their matched pairs) have been removed yet.
AGP_metadata=pd.read_table(metadata, sep='\t',
                     dtype=str)

In [66]:
AGP_metadata.head()

,sample_name,acid_reflux,acne_medication,acne_medication_otc,add_adhd,age_cat,age_corrected,age_years,alcohol_consumption,alcohol_frequency,...,vioscreen_zinc,vitamin_b_supplement_frequency,vitamin_d_supplement_frequency,vivid_dreams,weight_change,weight_kg,weight_units,whole_eggs,whole_grain_frequency,case
0,10317.000014564,I do not have this condition,FALSE,FALSE,I do not have this condition,50s,50,50,TRUE,Rarely (a few times/month),...,NaN,NaN,Daily,Rarely (a few times/month),Remained stable,50,kilograms,Rarely (less than once/week),Never,1
1,10317.000016350,"Diagnosed by a medical professional (doctor, p...",No,Yes,I do not have this condition,40s,45,45,Yes,Occasionally (1-2 times/week),...,Unspecified,Rarely (a few times/month),Rarely (a few times/month),Occasionally (1-2 times/week),Remained stable,81,kilograms,Occasionally (1-2 times/week),Occasionally (1-2 times/week),1
2,10317.000021693,I do not have this condition,FALSE,FALSE,I do not have this condition,teen,14,14,FALSE,Never,...,NaN,Never,Never,Occasionally (1-2 times/week),NaN,48,kilograms,Occasionally (1-2 times/week),Daily,1
3,10317.000023903,I do not have this condition,No,No,I do not have this condition,50s,52,52,Yes,Daily,...,NaN,Daily,Daily,Rarely (a few times/month),Remained stable,86,kilograms,Regularly (3-5 times/week),Regularly (3-5 times/week),1
4,10317.000023973,I do not have this condition,FALSE,TRUE,I do not have this condition,40s,40,40,TRUE,Occasionally (1-2 times/week),...,NaN,Rarely (a few times/month),Rarely (a few times/month),Never,Remained stable,72,kilograms,Regularly (3-5 times/week),Regularly (3-5 times/week),1

In [47]:
#BIOM table to DataFrame object
def exploding_panda(_bt):
    """BIOM->Pandas dataframe converter

    Parameters
    ----------
    _bt : biom.Table
        BIOM table

    Returns
    -------
    pandas.DataFrame
        The BIOM table converted into a DataFrame
        object.

    References
    ----------
    Based on this answer on SO:
    http://stackoverflow.com/a/17819427/379593
    """
    m = _bt.matrix_data
    data = [pd.SparseSeries(m[i].toarray().ravel()) for i in np.arange(m.shape[0])]
    out = pd.SparseDataFrame(data, index=_bt.ids('observation'),
                             columns=_bt.ids('sample'))

    return out

In [48]:
#The original filtered table
table2 = biom.load_table(filtered_table)

In [49]:
#Turn the original filtered BIOM table into a DataFrame object
biom_df = exploding_panda(table2)

In [50]:
biom_df.head()

,10317.000059045,10317.000041745,10317.000060344,10317.000033729,10317.000038129,10317.000058769,10317.000053381,10317.000041251,10317.000016493,10317.000029343,...,10317.000037946,10317.000039986,10317.000027840,10317.000042738,10317.000054004,10317.000039619,10317.000068288,10317.000046217,10317.000059111,10317.000038006
AACGTAGGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGCAGGCGGAAGGCTAAGTCTGATGTGAAAGCCCGGGGCTCAACCCCGGTACTGCATTGGAAACTGGTCATCTAGAGTG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGGTGCAAGCGTTGTCCGGAATCATTGGGCGTAAAGAGTTCGTAGGTGGTTTGTTAAGTTTGGTGTTAAATGCAGAGGCTCAACTTCTGTTCGGCATCGGATACTGGCAGACTAGAATG,0.0,4.0,42.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,...,0.0,0.0,26.0,0.0,8.0,0.0,0.0,36.0,0.0,3.0
TACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGACCATCAAGTCAGCGGTCAAAAGTCGGGGCTCAACCCCGTAAAGCCGTTGAAACTGGCGGTCTGGAGTGA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,701.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGATGGATGTTTAAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGATACTGGATATCTTGAGTG,288.0,19.0,1117.0,64.0,249.0,0.0,213.0,1806.0,0.0,358.0,...,270.0,49.0,2097.0,787.0,763.0,160.0,242.0,1308.0,1067.0,2398.0
TACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGTGCGTAGGTGGTGAGACAAGTCTGAAGTGAAAATCCGGGGCTTAACCCCGGAACTGCTTTGGAAACTGCCTGACTGGAGTA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
#Make a list of the values in the DataFrame
biom_df_list = biom_df.columns.values.tolist()

In [69]:
#Make a list of the sample ids from the metadata.
AGP_metadata_list = AGP_metadata['sample_name'].values.tolist()

In [71]:
#Convert the list into a set
biom_set = set(biom_df_list)

In [72]:
#Convert the list into a set
AGP_metadata_set = set(AGP_metadata_list)

In [73]:
#Determine which samples are 'missing'
missing = AGP_metadata_set - biom_set

In [74]:
#For every sample that is missing, print out the sample id and the corresponding case.
#This allows us to find the matched pair for each of the missing samples,
#Because both the missing sample and its matched pair must be deleted.
for i, entry in AGP_metadata['sample_name'].iteritems():
    for x in missing:
        if x in entry:
            print(entry, AGP_metadata['case'][i])

('10317.000016350', '1')
('10317.000023903', '1')
('10317.000039601', '1')
('10317.000046087', '1')
('10317.000051266', '1')
('10317.000058955', '1')
('10317.000063561', '1')
('10317.000038285', '0')
('10317.000039544', '0')
('10317.000039886', '0')
('10317.000041540', '0')
('10317.000058988', '0')

# Final filtering of the biom table
###### This filtering step uses the new filtered metadata that does not contain the missing samples or its matched pairs. This BIOM table ended up with 222 samples.

In [2]:
filtered_table_222=root+'Parse_biom_table/filtered_bc_table_222.biom'
!filter_samples_from_otu_table.py \
-i $table \
-o $filtered_table_222 \
--sample_id_fp $metadata_222

In [3]:
table_summary_222=root+'Parse_biom_table/filtered_bc_table_summary_222.txt'
!biom summarize-table -i $filtered_table_222 \
-o $table_summary_222